business_manager/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Джанговская система авторизации
    url(r'registration/', include('django.contrib.auth.urls', namespace='registration')),
    # Система профилей пользователей
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    # Доски с целями
    url(r'^purposes/', include('purposes.urls', namespace='purposes')),
    # Домашняя страница в приложении Launchers
    url(r'^', include('launchers.urls', namespace='launchers')),
]

business_manager/launchers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^$',
        view=views.home_page,
        name='home_page')
]

business_manager/profiles/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(regex=r'^register/$',
        view=views.RegisterUserFormView.as_view(),
        name='register'),
]

business_manager/purposes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(regex=r'^$',
        view=views.PurposesListView.as_view(),
        name='list'),
    url(regex=r'^add$',
        view=views.PurposeCreateView.as_view(),
        name='create'),
    url(regex=r'^(?P<pk>[0-9]+)/$',
        view=views.PurposeUpdateView.as_view(),
        name='edit')
]

business_manager/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """
    Абстрактный класс для добавления автообновляющихся полей
    даты создания и даты обновления в модель
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

business_manager/profiles/models.py
from django.db import models
from django.conf import settings


class Firm(models.Model):
    name = models.CharField(max_length=255)
    sphere = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    vocation = models.CharField(max_length=255)
    firm = models.ForeignKey(Firm)

    def __str__(self):
        return self.user.username

business_manager/purposes/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings

from core.models import TimeStampedModel


class Purpose(TimeStampedModel):
    title = models.CharField(max_length=255)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        ordering = ['-modified']

    def get_absolute_url(self):
        return reverse('purposes:list')

business_manager/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

business_manager/purposes/forms.py
from django import forms

from .models import Purpose


class PurposeForm(forms.ModelForm):

    class Meta:
        model = Purpose
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PurposeForm, self).__init__(*args, **kwargs)

business_manager/launchers/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, 'launchers/launcher_home_page.html')

business_manager/profiles/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login


class RegisterUserFormView(View):
    form_class = UserCreationForm
    template_name = 'profiles/profile_create_user.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return HttpResponseRedirect('/')
        return render(request, self.template_name, {'form': form})

business_manager/purposes/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Purpose
from .forms import PurposeForm


class PurposesListView(LoginRequiredMixin, ListView):
    model = Purpose
    login_url = reverse_lazy('registration:login')


class PurposeCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Purpose
    form_class = PurposeForm
    login_url = reverse_lazy('registration:login')
    success_url = reverse_lazy('purposes:list')
    success_message = 'Новая цель успешно создана!'

    def get_form_kwargs(self):
        kwargs = super(PurposeCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        purpose = form.save(commit=False)
        purpose.user = self.request.user
        purpose.save()
        super(PurposeCreateView, self).form_valid(form)
        return HttpResponseRedirect(self.success_url)


class PurposeUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Purpose
    template_name_suffix = '_update_form'
    fields = ['title', 'description']
    success_message = 'Данные успешно отредактированы!'
    login_url = reverse_lazy('registration:login')

business_manager/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {% block title %}Бизнес Менеджер{% endblock title %}
    </title>
    {% block stylesheets %}
        <link rel="stylesheet"
              type="text/css"
              href="{% static 'bootstrap/css/bootstrap.css' %}" />

        <link rel="stylesheet"
              type="text/css"
              href="{% static 'css/style.css' %}" />
    {% endblock stylesheets %}
</head>
<body>
    {% include 'loginbar.html' %}
    <hr/>
    <div class="container">
        {% block content %}
            <h1>Добро пожаловать в Бизнес Менеджер</h1>
        {% endblock content %}
    </div>
    <hr/>
    <div class="footer">
        <a href="{% url 'launchers:home_page' %}">На главную</a>
    </div>
    {% block javascripts_footer %}
        <script src="{% static 'js/jquery/jquery-2.2.3.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    {% endblock javascripts_footer %}
</body>
</html>

business_manager/templates/launchers/base_launchers.html
{% extends 'base.html' %}

business_manager/templates/launchers/launcher_home_page.html
{% extends 'launchers/base_launchers.html' %}
{% block content %}
    {{ block.super }}
    <p>
        <a href="{% url 'purposes:list' %}">Перейти к списку целей</a>
    </p>
{% endblock content %}

business_manager/templates/loginbar.html
<div>
    {% if user.is_authenticated %}
        <a href="{% url 'registration:logout' %}">Выйти</a>
        <p>Добро пожаловать {{ user.username }}</p>
    {% else %}
        <p>Войдите в систему или зарегистрируйтесь.</p>
        <a href="{% url 'registration:login' %}">Войти</a>
        <a href="{% url 'profiles:register' %}">Зарегистрироваться</a>
    {% endif %}
</div>

business_manager/templates/profiles/base_profiles.html
{% extends 'base.html' %}

business_manager/templates/profiles/profile_create_user.html
{% extends 'registration/base_registration.html' %}
{% block title %}Регистрация профиля{% endblock title %}
{% block content %}
    <div>
        Уже зарегистрированы? <a href="{% url 'registration:login' %}">Войти</a>
    </div>
    <div>
        <h1>Заполните форму для регистрации</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
        <p><input type="submit" value="Зарегистрироваться"></p>
    </form>
    </div>
{% endblock content %}

business_manager/templates/purposes/base_purposes.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}

business_manager/templates/purposes/purpose_board.html
{% extends 'purposes/base_purposes.html' %}
{% block title %}Доска целей{% endblock title %}
{% block content %}
    <p>{{ board }}</p>
    <p>
        <a href="{% url 'purposes:add_purpose' %}">Добавить цель</a>
    </p>
{% endblock content %}

business_manager/templates/purposes/purpose_form.html
{% extends 'purposes/base_purposes.html' %}
{% block title %}Добавить цель{% endblock title %}
{% block content %}
   <form action="" method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Сохранить">
   </form>
{% endblock content %}

business_manager/templates/purposes/purpose_list.html
{% extends 'purposes/base_purposes.html' %}
{% block title %}Доска целей{% endblock title %}
{% block content %}
    {{ block.super}}
    <h1>Цели</h1>
    <div class="container-fluid">
        {% for purpose in object_list %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">{{ purpose.title }}</h1>
                </div>
                <div class="panel-body">
                    {{ purpose.description }}
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Создано</th>
                            <th>Изменено</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ purpose.created }}</td>
                            <td>{{ purpose.modified }}</td>
                            <td><a href="{{ purpose.id }}"><small>Редактировать</small></a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        {% empty %}
            <p>Не нашлось целей. Вы можете добавить.</p>
        {% endfor %}
        <p>
            <a href="{% url 'purposes:create' %}">Создать</a>
        </p>
    </div>
{% endblock content %}

business_manager/templates/purposes/purpose_update_form.html
{% extends 'purposes/base_purposes.html' %}
{% block title %}Добавить цель{% endblock title %}
{% block content %}
   <form action="" method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Сохранить изменения">
   </form>
{% endblock content %}